### ISSUE TITLE
css/app.css is not found upon install

### ISSUE THREAD

**Issue by ryesio** [laravel/spark#77]
Default landing page looks bad.  Don't believe it was intentionally left off, so I made this ticket.

**Comment by aejnsn** [comment]
Try running gulp.

**Comment by ryesio** [comment]
When running gulp.

Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/vagrant/apotheosis/node_modules/laravel-elixir/index.js:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by aejnsn** [comment]
Sorry my previously reply was so brief, was commuting at that time.

I have a lot of problems with npm, one problem being it's slow as death. Easy button solution, drop your Node dependencies and reinstall:
`rm -rf node_modules/`
`npm install`

Then try to run `gulp` again.

**Comment by ryesio** [comment]
haha, no worries.  After your previous response, I went online to search for the answer to that and tried  the stuff you posted about in your response.  I'm getting the error:

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/vagrant/apotheosis
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! path /home/vagrant/apotheosis/node_modules/laravel-elixir/node_modules/gulp-rev-replace/node_modules/gulp-util/node_modules/dateformat/node_modules/meow/node_modules/indent-string/node_modules/repeating/node_modules/is-finite/node_modules/number-is-nan
npm ERR! fstream_path /home/vagrant/apotheosis/node_modules/laravel-elixir/node_modules/gulp-rev-replace/node_modules/gulp-util/node_modules/dateformat/node_modules/meow/node_modules/indent-string/node_modules/repeating/node_modules/is-finite/node_modules/number-is-nan
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code UNKNOWN
npm ERR! errno -1
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)

So I ran sudo npm install

npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm ERR! Error: UNKNOWN, symlink '../user-home/cli.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/vagrant/apotheosis
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! path ../user-home/cli.js
npm ERR! code UNKNOWN
npm ERR! errno -1
npm ERR! not ok code 0

Right now, I'm reinstalling Spark.

**Comment by aaranmcguire** [comment]
Your on a old version of node.. I had the same issue.. ![](https://pbs.twimg.com/media/CPdBwcaW8AEqrp6.png)

I then did `sudo npm update -g` & `sudo npm upgrade -g` started working after that.

**Comment by aejnsn** [comment]
I was getting ready to post what @aaranmcguire just posted. I was apparently running an ancient version of Node on another machine too, but my problems presented themselves differently.

**Comment by eduardocruz** [comment]
Just a +1 on the thread I ran into the same problem and I also realized that it was an NPM old version. The this is that I'm running a version of Homestead that I installed like one month ago. I didn't get why NPM is so old in it. Maybe it would be the case to open a ticket for Homestead (Even knowing that the person who opened this ticket here might not be running Homestead)

**Comment by ryesio** [comment]
I am actually running Homestead.  Haven't quite got it working yet, I'm going to open that ticket on Homestead.

**Comment by eduardocruz** [comment]
@ryesio In my case I got the solution here, after upgrading NPM: https://laracasts.com/discuss/channels/general-discussion/npm-install-error-inside-homestead-machine

> I've just solved my problem. This was my code in package.json

    {
      "private": true,
      "devDependencies": {
        "gulp": "^3.8.8",
        "laravel-elixir": "*"
      }
    }

> I don't know why I had the first line but I checked others laravel installation and I can see this line.

    {
      "devDependencies": {
        "gulp": "^3.8.8",
        "laravel-elixir": "*"
      }
    }

> I removed the first line and that's it... I run

    npm cache clean

> and then

    npm install

> and I could install gulp and laravel-elixir

**Comment by kayyyy** [comment]
did you install spark on an existing app or on a fresh laravel install?

**Comment by aaranmcguire** [comment]
Not sure about others, but when I had the issue it was on a fresh install.

**Comment by aejnsn** [comment]
Fresh install here as well. But my Node/npm version was ancient.

**Comment by eduardocruz** [comment]
@kayyyy In my case it was a fresh install. The problem as @aejnsn said was both "ancient" NPM on Homestead and the private attribute on package.json. I just realize that you can't even add an issue on Homestead requesting to upgrade npm before generating future installations. https://github.com/laravel/homestead

**Comment by cwt137** [comment]
The fix for a new Node and NPM has been in Homestead since June 30. Just look at the laravel/settler project. So, if you just build Homested from scratch, it will work. The reason why we don't see the changes in Homestead is that Taylor hasn't released a new version of Homestead to Atlas (think of it as a VM repository for Vagrant) in a few months. I had the same issue and I just ran "curl --silent --location https://deb.nodesource.com/setup_0.12 | sudo bash -" to upgrade Node and NPM.

**Comment by aejnsn** [comment]
Excellent. Thanks Christoper!

**Comment by ryesio** [comment]
Ok, so I did what @cwt137 stated. 
After which I ran "sudo apt-get install nodejs"
Then had to manually pull laravel-elixer as it didn't install after installing Laravel 5.1 and Spark.

Now I'm getting:
vagrant@homestead:~/apotheosis$ gulp
module.js:338
    throw err;
    ^

Error: Cannot find module 'browserify'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/vagrant/apotheosis/node_modules/laravel-elixir/tasks/browserify.js:7:18)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

I run "sudo npm install -g browserify" which appears to install.

vagrant@homestead:~/apotheosis$ sudo npm install -g browserify
/usr/local/bin/browserify -> /usr/local/lib/node_modules/browserify/bin/cmd.js
/usr/local/lib
└── browserify@11.1.0

After running gulp again though, 

vagrant@homestead:~/apotheosis$ gulp
module.js:338
    throw err;
    ^

Error: Cannot find module 'browserify'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/vagrant/apotheosis/node_modules/laravel-elixir/tasks/browserify.js:7:18)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by cweagans** [comment]
Same issue here:

* Fresh Laravel 5.1 installation (created with `laravel new myapp`)
* Fresh Spark installation (created with `spark install`)
* Fresh Homestead installation (this is the only app in Homestead)

**Comment by DanielGale** [comment]
#54 and #43  didn't help?

I had to make a symlink for node to work properly.

**Comment by cwt137** [comment]
A new Homestead has been Released! https://twitter.com/laravelphp/status/648262570093051905 https://atlas.hashicorp.com/laravel/boxes/homestead

**Comment by cweagans** [comment]
That fixed the issue! :+1:

**Comment by morrislaptop** [comment]
I have a similar problem, the source map files are not created once I run spark install - no idea why?!
